sudo: false

language: perl6
perl6:
  - latest
  - '2019.03'
  - '2020.05'

matrix:
  fast_finish: true
  allow_failures:
    - perl6: latest

branches:
  only:
    - master
    - devel

script:
  - vendor/iotester/bin/iotester -p
