sudo: false

language: perl6
perl6:
  - latest
  - '2017.07'
  - '2017.10'

matrix:
  fast_finish: true
  allow_failures:
    - perl6: latest

branches:
  only:
    - master
    - devel

script:
  - vendor/iotester/bin/iotester -p
